name: MiHomo-Alpha
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [android-arm64, linux-arm64]  # Matriks untuk kedua arsitektur
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: MetaCubeX/mihomo
          ref: Alpha
      
      - name: Get Latest tag
        id: latest_tag
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: MetaCubeX/mihomo
          excludes: prerelease, draft
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'
      
      - name: Install Android NDK (hanya untuk android-arm64)
        if: matrix.arch == 'android-arm64'
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip -d $HOME/android-ndk
          echo "ANDROID_NDK_HOME=$HOME/android-ndk/android-ndk-r25b" >> $GITHUB_ENV
      
      - name: Install aarch64-linux-gnu-gcc (hanya untuk linux-arm64)
        if: matrix.arch == 'linux-arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
      
      - name: Versioning
        run: |
          sudo timedatectl set-timezone "Asia/Jakarta"
          echo "NAME=mihomo" >> $GITHUB_ENV
          BUILDTIME=$(date)
          echo "BUILDTIME=$BUILDTIME" >> $GITHUB_ENV
          HASH_COMMIT=$(git rev-parse --short HEAD)
          TAG_RELEASE=${{ steps.latest_tag.outputs.release }}
          RELEASE_COMMIT_SHA=$(curl -s "https://api.github.com/repos/MetaCubeX/mihomo/git/ref/tags/${TAG_RELEASE}" | jq -r '.object.sha' | cut -c -7)
          VERSION=alpha-${HASH_COMMIT}
          
          echo "URL_CHANGE=https://www.github.com/metacubex/mihomo/compare/${RELEASE_COMMIT_SHA}...${HASH_COMMIT}" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAGS=with_gvisor,with_low_memory" >> $GITHUB_ENV
          echo "LDFLAGS=-X 'github.com/metacubex/mihomo/constant.Version=${VERSION}' -X 'github.com/metacubex/mihomo/constant.BuildTime=${BUILDTIME} ${TAG_RELEASE}' -w -s -buildid=" >> $GITHUB_ENV
      
      - name: Set Compiler and Environment Variables
        run: |
          if [ "${{ matrix.arch }}" == "android-arm64" ]; then
            echo "C_COMPILER=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang" >> $GITHUB_ENV
            echo "GOOS=android" >> $GITHUB_ENV
          elif [ "${{ matrix.arch }}" == "linux-arm64" ]; then
            echo "C_COMPILER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
            echo "GOOS=linux" >> $GITHUB_ENV
          fi
          echo "GOARCH=arm64" >> $GITHUB_ENV
      
      - name: Build
        run: |
          CGO_ENABLED=1 \
          CC=${{ env.C_COMPILER }} \
          GOARCH=${{ env.GOARCH }} \
          GOOS=${{ env.GOOS }} \
          go build -tags "${{ env.TAGS }}" \
          -trimpath \
          -ldflags "${{ env.LDFLAGS }}" \
          -o ./${NAME}-${{ matrix.arch }}
      
      - name: Archive
        id: archive
        run: |
          GZ="${NAME}-${{ matrix.arch }}-${VERSION}.tgz"
          tar -caf $GZ ./${NAME}-${{ matrix.arch }}
          echo "gz=$GZ" >> $GITHUB_OUTPUT
          SHA=$(sha256sum $GZ | cut -d ' ' -f1)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
      
      - name: Save Version
        run: |
          echo "${{ env.VERSION }}" > version.txt
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.arch }}"
          path: |
            *.tgz
            version.txt

  upload:
    permissions: write-all
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: bin/
      
      - name: Move to folder
        run: |
          mkdir release
          cp bin/android-arm64/* release/
          cp bin/linux-arm64/* release/
          ls -R release
      
      - name: Load VERSION
        run: |
          VERSION=$(cat release/version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          files: release/*
          prerelease: false
          generate_release_notes: true